services:
    tva:
        class: EP\EpapeterieBundle\Twig\Extension\TvaExtension
        tags:
            - {  name: twig.extension  }
    montantTva:
      class: EP\EpapeterieBundle\Twig\Extension\MontantTvaExtension
      tags:
        - { name: twig.extension }
    
    redirectionListener:
      class: EP\EpapeterieBundle\Listener\RedirectionListener
      arguments: [ @service_container, @session ]
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }