adminProduits:
    path:     /
    defaults: { _controller: "EPEpapetrieBundle:ProduitsAdmin:index" }

adminProduits_show:
    path:     /{id}/show
    defaults: { _controller: "EPEpapetrieBundle:ProduitsAdmin:show" }

adminProduits_new:
    path:     /new
    defaults: { _controller: "EPEpapetrieBundle:ProduitsAdmin:new" }

adminProduits_create:
    path:     /create
    defaults: { _controller: "EPEpapetrieBundle:ProduitsAdmin:create" }
    methods:  POST

adminProduits_edit:
    path:     /{id}/edit
    defaults: { _controller: "EPEpapetrieBundle:ProduitsAdmin:edit" }

adminProduits_update:
    path:     /{id}/update
    defaults: { _controller: "EPEpapetrieBundle:ProduitsAdmin:update" }
    methods:  [POST, PUT]

adminProduits_delete:
    path:     /{id}/delete
    defaults: { _controller: "EPEpapetrieBundle:ProduitsAdmin:delete" }
    methods:  [POST, DELETE]
